### ISSUE TITLE
Shortcode tutorial talks about widgets

### ISSUE THREAD

**Issue by cdCorey** [piklist/Piklist-Documentation#10]
https://docs.piklist.com/tutorials/shortcodes/getting-started-with-shortcodes/

Shortcode tutorial talks about creating widgets. Widgets and shortcodes are two different things. This is confusing.

**Comment by sbruner** [comment]
whoops!  Thanks for finding that.

Fixed: https://docs.piklist.com/tutorials/shortcodes/getting-started-with-shortcodes/
