### ISSUE TITLE
array parenthesis missing

### ISSUE THREAD

**Issue by coder618** [piklist/Piklist-Documentation#17]
add_filter('piklist_taxonomies', 'demo_type_tax');
  function demo_type_tax($taxonomies) {
     $taxonomies[] = array(
        'post_type' => 'piklist_demo'
        ,'name' => 'piklist_demo_type'
        ,'show_admin_column' => true
        ,'configuration' => array(
          'hierarchical' => true
          ,'labels' => piklist('taxonomy_labels', 'Demo Type')
          ,'hide_meta_box' => true
          ,'show_ui' => true
          ,'query_var' => true
          ,'rewrite' => array(
            'slug' => 'demo-type'
          )
      );
    return $taxonomies;
  }

**Comment by sbruner** [comment]
Where is this from? It looks fine in the repo:
https://github.com/piklist/piklist/blob/develop/add-ons/piklist-demos/piklist-demos.php#L87-L107

**Comment by sbruner** [comment]
found it. Thanks!
demo_type_tax
