### ISSUE TITLE
Piklist With Gutenberg Problem 

### ISSUE THREAD

**Issue by anower93** [piklist/Piklist-Documentation#30]
When I use Piklist, It works fine in WordPress Classic editor. 
When I use in Gutenberg, It doesn't work properly. 
Data doesn't save. I want to use it with Gutenberg. Thanks.

**Comment by sbruner** [comment]
@anower93 -- thank you for using Piklist.  Version 1.0.X does not support Gutenberg. This is listed on the plugin page: https://wordpress.org/plugins/piklist/

> Piklist 2.0 is coming soon with full Gutenberg support. Until then, please use the Classic Editor plugin when using WordPress 5.0+.
