### ISSUE TITLE
Folder structure not working on a plugin's folder

### ISSUE THREAD

**Issue by marcelCarpinter** [piklist/Piklist-Documentation#31]
Hi,

I am creating a plugin for a custom post type that I am using on my web, and I added within the plugin's folder the folders:
add-ons
parts

As suggested on the documentation, but the fields are not showing on the custom post type. When adding the same files on the theme's folder they appear

**Comment by sbruner** [comment]
Did you include “Plugin Type: Piklist”  in the plugin header?
https://docs.piklist.com/getting-started/writing-a-plugin-for-piklist/

**Comment by marcelCarpinter** [comment]
Oh, I totally miss that part. My Bad.
Thanks for the help and the quick response!

**Comment by sbruner** [comment]
Glad I could help. 

If you have a few minutes please leave a review for Piklist. It really helps the project: https://wordpress.org/support/plugin/piklist/reviews/

**Comment by marcelCarpinter** [comment]
Done!
