### ISSUE TITLE
Building a Simple Admin Page Tutorial

### ISSUE THREAD

**Issue by uandidezign** [piklist/Piklist-Documentation#9]
I just discovered Piklist and find the framework very interesting. However, this first tutorial does not seem to be giving me the results. First issue, the code snippet to register the admin page has double commas. After correcting that, I followed the rest of the tutorial and it didn't add a menu title to the admin menu. Below are the steps I took.

- Plugin installed and activated
- Made a copy of Piklist folder and installed it in my child theme folder
- Created the about.php and added the comments and code and placed it in parts/admin-page.

Did I miss anything? I also tried these steps directly on the parent theme and got the same result.

**Comment by sbruner** [comment]
Thank you for letting us know about the typo, we fixed it:
https://docs.piklist.com/tutorials/admin-pages/creating-a-simple-admin-page/

Here's what you should be doing. Please let me know if it's not clear in the tutorial:

- Plugin installed and activated
- Add code from tutorial in your child themes `functions.php` file.
- Add this folder structure in your child theme:  `main-theme-folder/piklist/parts/admin-pages/`
- Create a file called `about.php` in that folder. Should looks like: 
`main-theme-folder/piklist/parts/admin-pages/about.php`
-Add the code from the tutorial

Let me know if that helps.

**Comment by uandidezign** [comment]
Wow! Thanks for the fast response. And yea no problem. 

And your instructions worked perfectly. However, as you may already know, keeping files and folder in the parent theme is never a good idea. especially with the theme I use (they literally have updates every other week). So the question is, how do I go about using this framework in my child theme?

**Comment by uandidezign** [comment]
Forgot to mention. Adding custom post types and assigning meta boxes and fields via your functions, are working within my child theme.

**Comment by sbruner** [comment]
Great! Glad it worked.

You can just add the Piklist folder structure to your child theme:
`child-theme-folder/piklist/parts/admin-pages/`

**Comment by uandidezign** [comment]
I did that man, lol. It's not working. It only worked (as far as the admin page is concerned) when I moved the piklist folder to the parent theme directory.

I know it's late and don't expect a solution now. But it might be a bug. When you have sec, try to replicate the problem. 

And thanks for the quick response. I appreciate your time and support. I think you may something special here. Won't know for sure until I really dig in. But so far, so good and it's only been one day. Was able to do a lot and wanna see how far the rabbit hole goes.

Night,

**Comment by uandidezign** [comment]
Forget it. I see what the problem was. You added a new line right?

      ,'capability' => 'manage_options'

So I attributed the "About" admin label appearing to moving the Piklist folder to the parent directory when it was the missing code.

So the short, works perfectly within a child theme. Man, I hope that typo didn't deter first time users. As I was pulling my hair kinda lol.

Anyway, thanks again for your help and hopefully I can provide some constructive feedback in the coming days.

**Comment by sbruner** [comment]
Glad it worked. Going to close this ticket.
